# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# added some dummy parameters just in case we would need, I dont think we will, initially

name: Run E2E Tests - Soar Assignment

on:
  pull_request:
    types: [opened, ready_for_review]
  workflow_dispatch:
    inputs:
      environment:
        description: 'environment'
        default: 'staging'      
      
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
    
    - run: npx playwright test
